trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'BrowserStack'

container: dipjyotimetia/hybridtestframework:2.0

steps:

  - script: |
      chmod +x ./Driver/linux/chromedriver
      chmod +x ./Driver/linux/geckodriver
    displayName: 'Provide permissions'
  - bash: echo Providing env variables
  - script: gradle task e2e
    env:
      BROWSERSTACK_USERNAME: $(BROWSERSTACK_USERNAME)
      BROWSERSTACK_ACCESS_KEY: $(BROWSERSTACK_ACCESS_KEY)
    displayName: 'Running end to end test'
  - task: BrowserStackConfig@0
    inputs:
      BrowserStackServiceEndPoint: 'BrowserStack'
  - task: BrowserStackResults@0