version: '3'

services:
  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:8088"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "8088:8080" # from local machine the app will be accessible at http://localhost:8088

